### ISSUE TITLE
Frontend rpc endpoint error

### ISSUE THREAD

**Issue by TaylorDurden** [AbstractSDK/templates#83]
I stuck in a network error for rpc endpoint in testnet when the application was requesting by abstract hooks.
It turns out request https://neutron-testnet-rpc.polkachu.com/ then redirect to http://127.0.0.1:8545

<img width="1828" alt="image" src="https://github.com/user-attachments/assets/2d629b49-0107-4c78-adfa-25b3e7eb5e62">
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/cab35cb7-e182-4945-a872-7e1c191fac39">
<img width="778" alt="image" src="https://github.com/user-attachments/assets/291e4ce5-d61f-4cec-a0ec-aa4497ab2cbe">
<img width="1423" alt="image" src="https://github.com/user-attachments/assets/0327ce46-b3e1-4503-a244-479fc4ab4773">

**Comment by adairrr** [comment]
THis seems to be an issue with the polkachu endpoint itself.

To solve this, you can update the RPC endpoint used in the GrazProvider as such:
```
<GrazProvider
      grazOptions={{
        chains: [
          {
            ...testnetChains.neutrontestnet,
            rpc: 'https://rpc-falcron.pion-1.ntrn.tech',
          },
        ],
      }}
...
```
